/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package backend.fenetre;

import com.mysql.cj.jdbc.exceptions.CommunicationsException;
import java.awt.CardLayout;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Aro
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private Connection connexion;

    //Declaration des composants IHM
    private PanelConnexion panelConnexion;
    private CardLayout cardLayout;

    /**
     * Creates new form Main
     */
    public MenuPrincipal() {
        initComponents();
        initComponentPerso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        panelUtilisateurs = new javax.swing.JPanel();
        panelUtilisateur = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CBUtilisateurs = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        BBan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        rechercheUtilisateur = new javax.swing.JTextField();
        panelCreateEvent = new javax.swing.JPanel();
        panelPlats = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        CBPlats = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        BValider = new javax.swing.JButton();
        BSupprimer = new javax.swing.JButton();
        ChBValide = new javax.swing.JCheckBox();
        ChBSoumis = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        recherchePlat = new javax.swing.JTextField();
        panelEvenement = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        CBEvenement = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        BSupprimer1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        rechercheEvenement = new javax.swing.JTextField();
        panelAjoutIngredient = new javax.swing.JPanel();
        panelIngredient = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        CBIngredient = new javax.swing.JComboBox<>();
        jButton12 = new javax.swing.JButton();
        BSupprimer2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        rechercheIngredient = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trouve Ton Plat - Admin");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setText("Gérer les utilisateurs");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Gérer les plats");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Créer un évènement");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Quitter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Connexion");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setText("Modération");

        jLabel4.setText("Évènements");

        jButton8.setText("Gérer les évènements");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton7.setText("Ajouter un ingrédient");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel5.setText("Ingrédients");

        jButton9.setText("Gérer les ingrédients");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel3.setLayout(new java.awt.CardLayout());

        panelUtilisateurs.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelUtilisateurLayout = new javax.swing.GroupLayout(panelUtilisateur);
        panelUtilisateur.setLayout(panelUtilisateurLayout);
        panelUtilisateurLayout.setHorizontalGroup(
            panelUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 979, Short.MAX_VALUE)
        );
        panelUtilisateurLayout.setVerticalGroup(
            panelUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        panelUtilisateurs.add(panelUtilisateur, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Utilisateurs :");

        CBUtilisateurs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBUtilisateurs.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBUtilisateursItemStateChanged(evt);
            }
        });
        CBUtilisateurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBUtilisateursActionPerformed(evt);
            }
        });

        jButton5.setText("Rechercher");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        BBan.setText("Bannir/Debannir");
        BBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBanActionPerformed(evt);
            }
        });

        jLabel3.setText("Rechercher un utilisateur :");

        rechercheUtilisateur.setForeground(new java.awt.Color(102, 102, 102));
        rechercheUtilisateur.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rechercheUtilisateurFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rechercheUtilisateurFocusLost(evt);
            }
        });
        rechercheUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheUtilisateurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBUtilisateurs, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rechercheUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                        .addComponent(BBan, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BBan)
                    .addComponent(jButton5)
                    .addComponent(jLabel3)
                    .addComponent(rechercheUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBUtilisateurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelUtilisateurs.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(panelUtilisateurs, "card2");

        panelCreateEvent.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout panelCreateEventLayout = new javax.swing.GroupLayout(panelCreateEvent);
        panelCreateEvent.setLayout(panelCreateEventLayout);
        panelCreateEventLayout.setHorizontalGroup(
            panelCreateEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 979, Short.MAX_VALUE)
        );
        panelCreateEventLayout.setVerticalGroup(
            panelCreateEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );

        jPanel3.add(panelCreateEvent, "card3");

        panelPlats.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 979, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        panelPlats.add(jPanel4, java.awt.BorderLayout.CENTER);

        jLabel16.setText("Plats :");

        CBPlats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBPlats.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBPlatsItemStateChanged(evt);
            }
        });
        CBPlats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPlatsActionPerformed(evt);
            }
        });

        jButton10.setText("Rechercher");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        BValider.setText("Valider");
        BValider.setEnabled(false);
        BValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValiderActionPerformed(evt);
            }
        });

        BSupprimer.setText("Supprimer");
        BSupprimer.setEnabled(false);
        BSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSupprimerActionPerformed(evt);
            }
        });

        ChBValide.setSelected(true);
        ChBValide.setText("Plats Validés ");
        ChBValide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChBValideActionPerformed(evt);
            }
        });

        ChBSoumis.setSelected(true);
        ChBSoumis.setText("Plats Soumis");
        ChBSoumis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChBSoumisActionPerformed(evt);
            }
        });

        jLabel13.setText("Rechercher un plat :");

        recherchePlat.setForeground(new java.awt.Color(102, 102, 102));
        recherchePlat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                recherchePlatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                recherchePlatFocusLost(evt);
            }
        });
        recherchePlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recherchePlatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recherchePlat, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                                .addComponent(BSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BValider, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(ChBValide)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ChBSoumis)))
                        .addGap(12, 12, 12))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BValider)
                    .addComponent(BSupprimer)
                    .addComponent(jLabel13)
                    .addComponent(recherchePlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChBValide)
                    .addComponent(ChBSoumis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelPlats.add(jPanel7, java.awt.BorderLayout.NORTH);

        jPanel3.add(panelPlats, "card2");

        panelEvenement.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 979, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelEvenement.add(jPanel2, java.awt.BorderLayout.CENTER);

        jLabel17.setText("Evenement :");

        CBEvenement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        CBEvenement.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBEvenementItemStateChanged(evt);
            }
        });
        CBEvenement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBEvenementActionPerformed(evt);
            }
        });

        jButton11.setText("Rechercher");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        BSupprimer1.setText("Supprimer");
        BSupprimer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSupprimer1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Rechercher un évènement :");

        rechercheEvenement.setForeground(new java.awt.Color(102, 102, 102));
        rechercheEvenement.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rechercheEvenementFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rechercheEvenementFocusLost(evt);
            }
        });
        rechercheEvenement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheEvenementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rechercheEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BSupprimer1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSupprimer1)
                    .addComponent(jLabel14)
                    .addComponent(rechercheEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelEvenement.add(jPanel8, java.awt.BorderLayout.NORTH);

        jPanel3.add(panelEvenement, "card5");

        javax.swing.GroupLayout panelAjoutIngredientLayout = new javax.swing.GroupLayout(panelAjoutIngredient);
        panelAjoutIngredient.setLayout(panelAjoutIngredientLayout);
        panelAjoutIngredientLayout.setHorizontalGroup(
            panelAjoutIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 979, Short.MAX_VALUE)
        );
        panelAjoutIngredientLayout.setVerticalGroup(
            panelAjoutIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );

        jPanel3.add(panelAjoutIngredient, "card6");

        panelIngredient.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 979, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        panelIngredient.add(jPanel5, java.awt.BorderLayout.CENTER);

        jLabel18.setText("Ingrédients :");

        CBIngredient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        CBIngredient.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBIngredientItemStateChanged(evt);
            }
        });
        CBIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBIngredientActionPerformed(evt);
            }
        });

        jButton12.setText("Rechercher");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        BSupprimer2.setText("Supprimer");
        BSupprimer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSupprimer2ActionPerformed(evt);
            }
        });

        jLabel15.setText("Rechercher un ingrédient :");

        rechercheIngredient.setForeground(new java.awt.Color(102, 102, 102));
        rechercheIngredient.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rechercheIngredientFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rechercheIngredientFocusLost(evt);
            }
        });
        rechercheIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheIngredientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rechercheIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BSupprimer2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSupprimer2)
                    .addComponent(jLabel15)
                    .addComponent(rechercheIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelIngredient.add(jPanel9, java.awt.BorderLayout.NORTH);

        jPanel3.add(panelIngredient, "card5");

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBUtilisateursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBUtilisateursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBUtilisateursActionPerformed

    private void BBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBanActionPerformed
        String item = (String) CBUtilisateurs.getSelectedItem();
        String idUtilisateur = item.split(" ")[0];
        if (BBan.getText().equals("Bannir")) {
            bannir(idUtilisateur);
        } else {
            debannir(idUtilisateur);
        }
        checkBan(idUtilisateur);

    }//GEN-LAST:event_BBanActionPerformed

    private void CBPlatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPlatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPlatsActionPerformed

    private void rechercheUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheUtilisateurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheUtilisateurActionPerformed

    private void rechercheUtilisateurFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rechercheUtilisateurFocusGained

    }//GEN-LAST:event_rechercheUtilisateurFocusGained

    private void rechercheUtilisateurFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rechercheUtilisateurFocusLost

    }//GEN-LAST:event_rechercheUtilisateurFocusLost

    private void CBUtilisateursItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBUtilisateursItemStateChanged
        String item = (String) CBUtilisateurs.getSelectedItem();
        String idUtilisateur = item.split(" ")[0];
        PanelUtilisateur temp = new PanelUtilisateur(this, idUtilisateur);

        checkBan(idUtilisateur);

        panelUtilisateurs.remove(0);
        panelUtilisateurs.add(temp, 0);
        panelUtilisateurs.revalidate();
    }//GEN-LAST:event_CBUtilisateursItemStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CBUtilisateurs.setModel(lister("idUtilisateur", "pseudoUtilisateur", "Utilisateur", "WHERE pseudoUtilisateur LIKE '%" + rechercheUtilisateur.getText() + "%'"));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String filtre = " ";
        System.out.println(ChBValide.isSelected());
        System.out.println(ChBSoumis.isSelected());
        if (ChBValide.isSelected() || ChBSoumis.isSelected()) {
            filtre += " AND ";
            if (ChBValide.isSelected()) {
                filtre += "Ajoutee = '1'";
            }
            if (ChBValide.isSelected() && ChBSoumis.isSelected()) {
                filtre += " OR ";
            }
            if (ChBSoumis.isSelected()) {
                filtre += "Ajoutee = '0'";
            }
            System.out.println(filtre);
        }
        CBPlats.setModel(lister("idPlat", "Nom", "Plat", "WHERE Nom LIKE '%" + recherchePlat.getText() + "%'" + filtre));
    }//GEN-LAST:event_jButton10ActionPerformed

    private void ChBValideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChBValideActionPerformed

    }//GEN-LAST:event_ChBValideActionPerformed

    private void ChBSoumisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChBSoumisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChBSoumisActionPerformed

    private void BSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSupprimerActionPerformed
        String item = (String) CBPlats.getSelectedItem();
        String idPlat = item.split(" ")[0];

        supprimerPlat(idPlat);
    }//GEN-LAST:event_BSupprimerActionPerformed

    private void BValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValiderActionPerformed
        String item = (String) CBPlats.getSelectedItem();
        String idPlat = item.split(" ")[0];
        valider(idPlat);
    }//GEN-LAST:event_BValiderActionPerformed

    private void recherchePlatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_recherchePlatFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_recherchePlatFocusGained

    private void recherchePlatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_recherchePlatFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_recherchePlatFocusLost

    private void recherchePlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recherchePlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recherchePlatActionPerformed

    private void CBPlatsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBPlatsItemStateChanged
        String item = (String) CBPlats.getSelectedItem();
        String idPlat = item.split(" ")[0];

        BValider.setEnabled(!estValide(idPlat));
        BSupprimer.setEnabled(true);

        PanelPlat temp = new PanelPlat(this, idPlat);
        panelPlats.remove(0);
        panelPlats.add(temp, 0);
        panelPlats.revalidate();
    }//GEN-LAST:event_CBPlatsItemStateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        cardLayout.show(jPanel3, "C");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cardLayout.show(jPanel3, "E");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cardLayout.show(jPanel3, "P");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cardLayout.show(jPanel3, "U");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        cardLayout.show(jPanel3, "ME");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void CBEvenementItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBEvenementItemStateChanged
        String item = (String) CBEvenement.getSelectedItem();
        String idEvent = item.split(" ")[0];

        PanelEvenement temp = new PanelEvenement(this, idEvent);
        panelEvenement.remove(0);
        panelEvenement.add(temp, 0);
        panelEvenement.revalidate();
    }//GEN-LAST:event_CBEvenementItemStateChanged

    private void CBEvenementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBEvenementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBEvenementActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        CBEvenement.setModel(lister("IdEvenement", "NomEvenement", "Evenement", "WHERE NomEvenement LIKE '%" + rechercheEvenement.getText() + "%'"));
    }//GEN-LAST:event_jButton11ActionPerformed

    private void BSupprimer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSupprimer1ActionPerformed
        String item = (String) CBEvenement.getSelectedItem();
        String idEvent = item.split(" ")[0];

        supprimerEvent(idEvent);
    }//GEN-LAST:event_BSupprimer1ActionPerformed

    private void rechercheEvenementFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rechercheEvenementFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheEvenementFocusGained

    private void rechercheEvenementFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rechercheEvenementFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheEvenementFocusLost

    private void rechercheEvenementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheEvenementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheEvenementActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        cardLayout.show(jPanel3, "AI");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        cardLayout.show(jPanel3, "I");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void CBIngredientItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBIngredientItemStateChanged
        String item = (String) CBIngredient.getSelectedItem();
        String idIngredient = item.split(" ")[0];

        PanelIngredient temp = new PanelIngredient(this, idIngredient);
        panelEvenement.remove(0);
        panelEvenement.add(temp, 0);
        panelEvenement.revalidate();
    }//GEN-LAST:event_CBIngredientItemStateChanged

    private void CBIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBIngredientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBIngredientActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        CBIngredient.setModel(lister("idIngredient", "Nom", "Ingredient", "WHERE Nom LIKE '%" + rechercheIngredient.getText() + "%'"));
    }//GEN-LAST:event_jButton12ActionPerformed

    private void BSupprimer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSupprimer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BSupprimer2ActionPerformed

    private void rechercheIngredientFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rechercheIngredientFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheIngredientFocusGained

    private void rechercheIngredientFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rechercheIngredientFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheIngredientFocusLost

    private void rechercheIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheIngredientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheIngredientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuPrincipal mp = new MenuPrincipal();
                //mp.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBan;
    private javax.swing.JButton BSupprimer;
    private javax.swing.JButton BSupprimer1;
    private javax.swing.JButton BSupprimer2;
    private javax.swing.JButton BValider;
    private javax.swing.JComboBox<String> CBEvenement;
    private javax.swing.JComboBox<String> CBIngredient;
    private javax.swing.JComboBox<String> CBPlats;
    private javax.swing.JComboBox<String> CBUtilisateurs;
    private javax.swing.JCheckBox ChBSoumis;
    private javax.swing.JCheckBox ChBValide;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel panelAjoutIngredient;
    private javax.swing.JPanel panelCreateEvent;
    private javax.swing.JPanel panelEvenement;
    private javax.swing.JPanel panelIngredient;
    private javax.swing.JPanel panelPlats;
    private javax.swing.JPanel panelUtilisateur;
    private javax.swing.JPanel panelUtilisateurs;
    private javax.swing.JTextField rechercheEvenement;
    private javax.swing.JTextField rechercheIngredient;
    private javax.swing.JTextField recherchePlat;
    private javax.swing.JTextField rechercheUtilisateur;
    // End of variables declaration//GEN-END:variables

    private void initComponentPerso() {

        cardLayout = new CardLayout();
        panelConnexion = new PanelConnexion();
        panelCreateEvent = new PanelCreationEvenement(this);
        panelAjoutIngredient = new PanelAjoutIngredient(this);

        jPanel3.setLayout(cardLayout);
        jPanel3.add(panelUtilisateurs, "U");
        jPanel3.add(panelPlats, "P");
        jPanel3.add(panelCreateEvent, "E");
        jPanel3.add(panelEvenement, "ME");
        jPanel3.add(panelConnexion, "C");
        jPanel3.add(panelAjoutIngredient, "AI");
        jPanel3.add(panelIngredient, "I");

        CBUtilisateurs.setModel(lister("idUtilisateur", "pseudoUtilisateur", "Utilisateur", "WHERE pseudoUtilisateur LIKE '%" + rechercheUtilisateur.getText() + "%'"));
        CBPlats.setModel(lister("idPlat", "nom", "Plat", ""));
        CBEvenement.setModel(lister("IdEvenement", "NomEvenement", "Evenement", "WHERE NomEvenement LIKE '%" + rechercheEvenement.getText() + "%'"));
        CBIngredient.setModel(lister("idIngredient", "Nom", "Ingredient", "WHERE Nom LIKE '%" + rechercheIngredient.getText() + "%'"));
    }

    public DefaultComboBoxModel lister(String nomId, String nom, String table, String where) {
        String[] liste = new String[1];
        int nb = 0;

        try {
            Statement nomOrdre = connect();

            ResultSet resultat = nomOrdre.executeQuery("SELECT COUNT(" + nomId + ") FROM " + table + " " + where);
            while (resultat.next()) {
                nb = resultat.getInt(1);
            }
            liste = new String[nb];
            resultat = nomOrdre.executeQuery("SELECT " + nomId + ", " + nom + " FROM " + table + " " + where + "ORDER BY " + nomId);
            int cpt = 0;
            while (resultat.next()) {
                liste[cpt] = resultat.getString(nomId) + " - " + resultat.getString(nom);
                cpt++;
            }

            resultat.close();
            nomOrdre.close();

        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        return new DefaultComboBoxModel(liste);
    }

    /**
     * Ne sert à rien
     *
     * @param sql
     */
    public void requeteLocalhost(String requete) {
        // TODO code application logic here

        try {
            // TODO code application logic here
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connexion = DriverManager.getConnection("jdbc:mysql://" + this.panelConnexion.getBDHost() + "/" + this.panelConnexion.getBDDBName(), this.panelConnexion.getBDUser(), this.panelConnexion.getBDPWD());
            Statement nomOrdre = connexion.createStatement();
            ResultSet resultat = nomOrdre.executeQuery("SELECT nom FROM Plat");
            while (resultat.next()) {
                var nom = resultat.getArray("nom");
                System.out.println(nom);
            }
            resultat.close();
            nomOrdre.close();
            connexion.close();
        } catch (SQLException ex) {
            System.out.println("Impossible de se connecter a la base");
            System.exit(0);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public Statement connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            connexion = DriverManager.getConnection("jdbc:mysql://" + this.panelConnexion.getBDHost() + "/" + this.panelConnexion.getBDDBName(), this.panelConnexion.getBDUser(), this.panelConnexion.getBDPWD());
            return connexion.createStatement();
        } catch (CommunicationsException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Probleme de connexion à la base de donnee");
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    public PreparedStatement connectPrepared(String sql) {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            connexion = DriverManager.getConnection("jdbc:mysql://" + this.panelConnexion.getBDHost() + "/" + this.panelConnexion.getBDDBName(), this.panelConnexion.getBDUser(), this.panelConnexion.getBDPWD());
            return connexion.prepareStatement(sql);
        } catch (CommunicationsException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Probleme de connexion à la base de donnee");
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    private void bannir(String idUtilisateur) {
        Statement nomOrdre = connect();
        try {
            nomOrdre.executeUpdate("UPDATE Utilisateur SET statutBan = " + true + " WHERE idUtilisateur = " + idUtilisateur);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void debannir(String idUtilisateur) {
        Statement nomOrdre = connect();
        try {
            nomOrdre.executeUpdate("UPDATE Utilisateur SET statutBan = " + false + " WHERE idUtilisateur = " + idUtilisateur);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean estBan(String idUtilisateur) {
        boolean statutBan = false;
        try {

            Statement nomOrdre = connect();
            ResultSet resultat = nomOrdre.executeQuery("SELECT statutBan FROM Utilisateur WHERE idUtilisateur = " + idUtilisateur);

            while (resultat.next()) {
                statutBan = resultat.getBoolean("statutBan");
            }

        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        return statutBan;
    }

    private void checkBan(String idUtilisateur) {
        if (estBan(idUtilisateur)) {
            BBan.setText("Debannir");
        } else {
            BBan.setText("Bannir");
        }
    }

    private boolean estValide(String idPlat) {
        boolean ajoutee = false;
        try {

            Statement nomOrdre = connect();
            ResultSet resultat = nomOrdre.executeQuery("SELECT Ajoutee FROM Plat WHERE idUtilisateur = " + idPlat);

            while (resultat.next()) {
                ajoutee = resultat.getBoolean("Ajoutee");
            }

        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        return ajoutee;
    }

    private void supprimerPlat(String idPlat) {
        try {
            Statement nomOrdre = connect();
            nomOrdre.executeUpdate("DELETE FROM Plat WHERE IdPlat = '" + idPlat + "'");

        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void supprimerEvent(String idEvent) {
        try {
            Statement nomOrdre = connect();
            nomOrdre.executeUpdate("DELETE FROM Evenement WHERE idEvent = '" + idEvent + "'");
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void supprimerIngredient(String idIngredient) {
        try {
            Statement nomOrdre = connect();
            nomOrdre.executeUpdate("DELETE FROM Ingredient WHERE idIngredient = '" + idIngredient + "'");
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void valider(String idPlat) {
        Statement nomOrdre = connect();
        try {
            nomOrdre.executeUpdate("UPDATE Plat SET Ajoutee = '1' WHERE IdPlat = '" + idPlat + "'");
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
