/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package backend.fenetre;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Aro
 */
public class PanelUtilisateur extends javax.swing.JPanel {

    private MenuPrincipal menuPrincipal;

    /**
     * Creates new form PanelUtilisateur
     */
    public PanelUtilisateur(MenuPrincipal menuPrincipal, String idUtilisateur) {
        initComponents();
        this.menuPrincipal = menuPrincipal;
        afficher(idUtilisateur);
    }

    public PanelUtilisateur(String Pseudo, String Description, String[] CBPSoumis, String[] CBPFavoris, String avatar) {
        initComponents();
        this.CBPFavoris.setModel(new DefaultComboBoxModel(CBPFavoris));
        this.CBPSoumis.setModel(new DefaultComboBoxModel(CBPSoumis));
        this.description.setText(Description);
        this.pseudo.setText(Pseudo);
        this.SPImage.remove(0);
        this.SPImage.add( new PanelImage("avatars\\" + avatar));
    }

    private void afficher(String idUtilisateur) {
        String[] platsSoumis = new String[1], platsFavoris = new String[1];
        String description = new String(), pseudo = new String(), avatar = new String();;
        int cpt = 0;

        Statement nomOrdre = menuPrincipal.connect();

        ResultSet resultat;
        try {
            //Vas chercher les informations de l'utilisateur
            resultat = nomOrdre.executeQuery("SELECT pseudoUtilisateur, description, avatar FROM Utilisateur WHERE idUtilisateur = '" + idUtilisateur + "'");
            while (resultat.next()) {
                pseudo = resultat.getString("pseudoUtilisateur");
                description = resultat.getString("description");
                avatar = resultat.getString("avatar");
            }

            //Vas chercher les plats favoris de l'utilisateur
            resultat = nomOrdre.executeQuery("SELECT COUNT(idPlat) FROM Favoris WHERE IdUtilisateur = " + idUtilisateur);
            while (resultat.next()) {
                platsFavoris = new String[resultat.getInt(1)];
            }
            resultat = nomOrdre.executeQuery("SELECT p.IdPlat, Nom FROM Plat p, Favoris f WHERE f.IdUtilisateur = " + idUtilisateur + " AND p.IdPlat = f.IdPlat ORDER BY p.IdPlat");
            cpt = 0;
            while (resultat.next()) {
                platsFavoris[cpt] = resultat.getString("IdPlat") + " - " + resultat.getString("Nom");
                cpt++;
            }

            //Vas chercher les plats soumis par l'utilisateur
            resultat = nomOrdre.executeQuery("SELECT COUNT(idPlat) FROM Plat WHERE IdUtilisateur = " + idUtilisateur);
            while (resultat.next()) {
                platsSoumis = new String[resultat.getInt(1)];
            }

            resultat = nomOrdre.executeQuery("SELECT IdPlat, Nom FROM Plat WHERE IdUtilisateur = " + idUtilisateur + " ORDER BY IdPlat");

            cpt = 0;
            while (resultat.next()) {
                platsSoumis[cpt] = resultat.getString("IdPlat") + " - " + resultat.getString("Nom");
                cpt++;
            }

        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.CBPFavoris.setModel(new DefaultComboBoxModel(platsFavoris));
        this.CBPSoumis.setModel(new DefaultComboBoxModel(platsSoumis));
        this.description.setText(description);
        this.pseudo.setText(pseudo);
        this.SPImage.remove(0);
        this.SPImage.add( new PanelImage("avatars\\" + avatar + ".png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        CBPSoumis = new javax.swing.JComboBox<>();
        CBPFavoris = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        pseudo = new javax.swing.JLabel();
        SPImage = new javax.swing.JScrollPane();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Pseudonyme : ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Description :");

        description.setEditable(false);
        description.setColumns(20);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Plats soumis :");

        CBPSoumis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBPSoumis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPSoumisActionPerformed(evt);
            }
        });

        CBPFavoris.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBPFavoris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPFavorisActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Plats favoris :");

        pseudo.setText("Pseudo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SPImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pseudo)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBPSoumis, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBPFavoris, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(pseudo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SPImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(CBPSoumis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(CBPFavoris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CBPSoumisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPSoumisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPSoumisActionPerformed

    private void CBPFavorisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPFavorisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPFavorisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBPFavoris;
    private javax.swing.JComboBox<String> CBPSoumis;
    private javax.swing.JScrollPane SPImage;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pseudo;
    // End of variables declaration//GEN-END:variables

}
