/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package backend.fenetre;

/**
 *
 * @author Aro
 */
public class PanelConnexion extends javax.swing.JPanel {

    // Accès base de données DEFAULT
    /**
     * Variable correspondant à l'adresse de la base de donnée
     */
    private final String DEFAULT_BD_HOST = "mysql-trouvetonplat.alwaysdata.net";
    /**
     * Variable correspondant au nom de la base de donnée
     */
    private final String DEFAULT_BD_DBNAME = "trouvetonplat_bd";
    /**
     * Variable correspondant au nom d'utilisateur
     */
    private final String DEFAULT_BD_USERNAME = "289080";
    /**
     * Variable correspondant au mot de passe
     */
    private final String DEFAULT_BD_PASSWORD = "trouveton784512";
    
    // Accès base de données LAST
    /**
     * Variable correspondant à l'adresse de la base de donnée
     */
    private String lastBDHost;
    /**
     * Variable correspondant au nom de la base de donnée
     */
    private String lastBDDBName;
    /**
     * Variable correspondant au nom d'utilisateur
     */
    private String lastBDUsername;
    /**
     * Variable correspondant au mot de passe
     */
    private String lastBDPWD;
    
    // Accès base de données
    /**
     * Variable correspondant à l'adresse de la base de donnée
     */
    private String BDHost;
    /**
     * Variable correspondant au nom de la base de donnée
     */
    private String BDDBName;
    /**
     * Variable correspondant au nom d'utilisateur
     */
    private String BDUsername;
    /**
     * Variable correspondant au mot de passe
     */
    private String BDPWD;
    
    /**
     * Creates new form PanelConnexion
     */
    public PanelConnexion() {
        initComponents();
        this.lastBDHost = DEFAULT_BD_HOST;
        this.lastBDDBName = DEFAULT_BD_DBNAME;
        this.lastBDUsername = DEFAULT_BD_USERNAME;
        this.lastBDPWD = DEFAULT_BD_PASSWORD;
        defaultState();
    }

    public PanelConnexion(String BDHost, String BDDBName, String BDUser, String BDPWD) {
        initComponents();
        this.lastBDHost = BDHost;
        this.lastBDDBName = BDDBName;
        this.lastBDUsername = BDUser;
        this.lastBDPWD = BDPWD;
        this.BDHost = BDHost;
        this.BDDBName = BDDBName;
        this.BDUsername = BDUser;
        this.BDPWD = BDPWD;
    }

    public String getBDHost() {
        return BDHost;
    }

    public void setBDHost(String BDHost) {
        this.BDHost = BDHost;
    }

    public String getBDDBName() {
        return BDDBName;
    }

    public void setBDDBName(String BDDBName) {
        this.BDDBName = BDDBName;
    }

    public String getBDUser() {
        return BDUsername;
    }

    public void setBDUsername(String BDUser) {
        this.BDUsername = BDUser;
    }

    public String getBDPWD() {
        return BDPWD;
    }

    public void setBDPWD(String BDPWD) {
        this.BDPWD = BDPWD;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lHost = new javax.swing.JLabel();
        lDBName = new javax.swing.JLabel();
        lUser = new javax.swing.JLabel();
        lPWD = new javax.swing.JLabel();
        tfDBName = new javax.swing.JTextField();
        tfHost = new javax.swing.JTextField();
        tfUser = new javax.swing.JTextField();
        tfPWD = new javax.swing.JTextField();
        bAnnuler = new javax.swing.JButton();
        bDefault = new javax.swing.JButton();
        bSauvegarder = new javax.swing.JButton();

        lHost.setText("Nom d'hôte :");

        lDBName.setText("Nom de la base :");

        lUser.setText("Identifiant :");

        lPWD.setText("Mot de passe :");

        tfDBName.setText(getBDDBName());
        tfDBName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDBNameActionPerformed(evt);
            }
        });

        tfHost.setText(getBDHost());
        tfHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHostActionPerformed(evt);
            }
        });

        tfUser.setText(getBDUser());
        tfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserActionPerformed(evt);
            }
        });

        tfPWD.setText(getBDPWD());
        tfPWD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPWDActionPerformed(evt);
            }
        });

        bAnnuler.setText("Annuler");
        bAnnuler.setMaximumSize(new java.awt.Dimension(100, 25));
        bAnnuler.setMinimumSize(new java.awt.Dimension(100, 25));
        bAnnuler.setPreferredSize(new java.awt.Dimension(100, 25));
        bAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnnulerActionPerformed(evt);
            }
        });

        bDefault.setText("Default");
        bDefault.setMaximumSize(new java.awt.Dimension(100, 25));
        bDefault.setMinimumSize(new java.awt.Dimension(100, 25));
        bDefault.setPreferredSize(new java.awt.Dimension(100, 25));
        bDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDefaultActionPerformed(evt);
            }
        });

        bSauvegarder.setText("Sauvegarder");
        bSauvegarder.setMaximumSize(new java.awt.Dimension(100, 25));
        bSauvegarder.setMinimumSize(new java.awt.Dimension(100, 25));
        bSauvegarder.setPreferredSize(new java.awt.Dimension(100, 25));
        bSauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSauvegarderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lHost)
                            .addComponent(lDBName)
                            .addComponent(lUser)
                            .addComponent(lPWD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPWD, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfUser, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tfDBName, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tfHost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bSauvegarder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(bDefault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(bAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lHost)
                    .addComponent(tfHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDBName)
                    .addComponent(tfDBName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUser)
                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPWD)
                    .addComponent(tfPWD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSauvegarder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDefault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfDBNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDBNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDBNameActionPerformed

    private void tfHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHostActionPerformed

    private void tfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserActionPerformed

    private void tfPWDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPWDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPWDActionPerformed

    private void bAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnnulerActionPerformed
        this.setBDHost(this.lastBDHost);
        this.setBDDBName(this.lastBDDBName);
        this.setBDUsername(this.lastBDUsername);
        this.setBDPWD(this.lastBDPWD);
        this.tfHost.setText(this.lastBDHost);
        this.tfDBName.setText(this.lastBDDBName);
        this.tfUser.setText(this.lastBDUsername);
        this.tfPWD.setText(this.lastBDPWD);
    }//GEN-LAST:event_bAnnulerActionPerformed

    private void bDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDefaultActionPerformed
       defaultState();
    }//GEN-LAST:event_bDefaultActionPerformed

    private void bSauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSauvegarderActionPerformed
        this.setBDHost(tfHost.getText());
        this.setBDDBName(tfDBName.getText());
        this.setBDUsername(tfUser.getText());
        this.setBDPWD(tfPWD.getText());
    }//GEN-LAST:event_bSauvegarderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnnuler;
    private javax.swing.JButton bDefault;
    private javax.swing.JButton bSauvegarder;
    private javax.swing.JLabel lDBName;
    private javax.swing.JLabel lHost;
    private javax.swing.JLabel lPWD;
    private javax.swing.JLabel lUser;
    private javax.swing.JTextField tfDBName;
    private javax.swing.JTextField tfHost;
    private javax.swing.JTextField tfPWD;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables

    private void defaultState(){
        this.setBDHost(this.DEFAULT_BD_HOST);
        this.setBDDBName(this.DEFAULT_BD_DBNAME);
        this.setBDUsername(this.DEFAULT_BD_USERNAME);
        this.setBDPWD(this.DEFAULT_BD_PASSWORD);
        this.tfHost.setText(this.DEFAULT_BD_HOST);
        this.tfDBName.setText(this.DEFAULT_BD_DBNAME);
        this.tfUser.setText(this.DEFAULT_BD_USERNAME);
        this.tfPWD.setText(this.DEFAULT_BD_PASSWORD);
    }
}
