/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package backend.fenetre;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;

/**
 *
 * @author Aro
 */
public class PanelAjoutIngredient extends javax.swing.JPanel {

    private MenuPrincipal menuPrincipal;

    /**
     * Creates new form PanelAjoutIngredient
     */
    public PanelAjoutIngredient(MenuPrincipal menuPrincipal) {
        this.menuPrincipal = menuPrincipal;
        initComponents();
    }

    private void ajouterIngredient(String nomIngredient) {
        String sql = "INSERT INTO Ingredient (`Nom`) VALUES ('" + nomIngredient + "')";
        PreparedStatement nomOrdre = menuPrincipal.connectPrepared(sql);
        try {
            nomOrdre.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(PanelAjoutIngredient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean checkIngredient(String nomIngredient) {
        String sql = "SELECT COUNT(Nom) FROM Ingredient WHERE Nom = '" + nomIngredient + "'";
        Statement nomOrdre = menuPrincipal.connect();
        try {
            ResultSet resultat = nomOrdre.executeQuery(sql);
            while (resultat.next()) {
                if (resultat.getInt(1) >= 1) {
                    return true;
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(PanelAjoutIngredient.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TFIngredient = new javax.swing.JTextField();
        BIngredient = new javax.swing.JButton();

        jLabel1.setText("Nom de l'ingrédient :");

        TFIngredient.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFIngredientCaretUpdate(evt);
            }
        });
        TFIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFIngredientActionPerformed(evt);
            }
        });

        BIngredient.setText("Ajouter");
        BIngredient.setEnabled(false);
        BIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIngredientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BIngredient)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BIngredient))
                .addContainerGap(145, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIngredientActionPerformed
        ajouterIngredient(TFIngredient.getText());
        BIngredient.setEnabled(false);
    }//GEN-LAST:event_BIngredientActionPerformed

    private void TFIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFIngredientActionPerformed

    }//GEN-LAST:event_TFIngredientActionPerformed

    private void TFIngredientCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFIngredientCaretUpdate
        BIngredient.setEnabled(!checkIngredient(TFIngredient.getText()));
    }//GEN-LAST:event_TFIngredientCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BIngredient;
    private javax.swing.JTextField TFIngredient;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
