/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package backend.fenetre;

import javax.swing.JFrame;

/**
 *
 * @author Aro
 */
public class FrameConnexion extends javax.swing.JDialog {

    // Accès base de données
    /**
     * Variable correspondant à l'adresse de la base de donnée
     */
    private String BDHost;
    /**
     * Variable correspondant au nom de la base de donnée
     */
    private String BDDBName;
    /**
     * Variable correspondant au nom d'utilisateur
     */
    private String BDUser;
    /**
     * Variable correspondant au mot de passe
     */
    private String BDPWD;

    /**
     * Creates new form FrameConnexion
     */
    public FrameConnexion(JFrame frame) {
        super(frame);
        
        this.BDHost = "mysql-trouvetonplat.alwaysdata.net";
        this.BDDBName = "trouvetonplat_bd";
        this.BDUser = "289080";
        this.BDPWD = "trouveton784512";
        
        initComponents();
    }
    
    public FrameConnexion(JFrame frame, String BDHost, String BDDBName, String BDUser, String BDPWD){
        super(frame);
        
        this.BDHost = BDHost;
        this.BDDBName = BDDBName;
        this.BDUser = BDUser;
        this.BDPWD = BDPWD;
        
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lHost = new javax.swing.JLabel();
        lDBName = new javax.swing.JLabel();
        lUser = new javax.swing.JLabel();
        lPWD = new javax.swing.JLabel();
        tfDBName = new javax.swing.JTextField();
        tfHost = new javax.swing.JTextField();
        tfUser = new javax.swing.JTextField();
        tfPWD = new javax.swing.JTextField();
        bSauvegarder = new javax.swing.JButton();
        bAnnuler = new javax.swing.JButton();
        bAppliquer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuration de la connexion");

        lHost.setText("Nom d'hôte :");

        lDBName.setText("Nom de la base :");

        lUser.setText("Identifiant :");

        lPWD.setText("Mot de passe :");

        tfDBName.setText(BDDBName);
        tfDBName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDBNameActionPerformed(evt);
            }
        });

        tfHost.setText(BDHost);
        tfHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHostActionPerformed(evt);
            }
        });

        tfUser.setText(BDUser);
        tfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserActionPerformed(evt);
            }
        });

        tfPWD.setText(BDPWD);
        tfPWD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPWDActionPerformed(evt);
            }
        });

        bSauvegarder.setText("Sauvegarder");
        bSauvegarder.setMaximumSize(new java.awt.Dimension(100, 25));
        bSauvegarder.setMinimumSize(new java.awt.Dimension(100, 25));
        bSauvegarder.setPreferredSize(new java.awt.Dimension(100, 25));
        bSauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSauvegarderActionPerformed(evt);
            }
        });

        bAnnuler.setText("Annuler");
        bAnnuler.setMaximumSize(new java.awt.Dimension(100, 25));
        bAnnuler.setMinimumSize(new java.awt.Dimension(100, 25));
        bAnnuler.setPreferredSize(new java.awt.Dimension(100, 25));
        bAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnnulerActionPerformed(evt);
            }
        });

        bAppliquer.setText("Appliquer");
        bAppliquer.setMaximumSize(new java.awt.Dimension(100, 25));
        bAppliquer.setMinimumSize(new java.awt.Dimension(100, 25));
        bAppliquer.setPreferredSize(new java.awt.Dimension(100, 25));
        bAppliquer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAppliquerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bSauvegarder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(bAppliquer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(bAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lHost)
                            .addComponent(lDBName)
                            .addComponent(lUser)
                            .addComponent(lPWD))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPWD, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                .addComponent(tfDBName, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tfHost, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lHost)
                    .addComponent(tfHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDBName)
                    .addComponent(tfDBName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUser)
                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPWD)
                    .addComponent(tfPWD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSauvegarder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAppliquer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDBNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDBNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDBNameActionPerformed

    private void tfHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHostActionPerformed

    private void tfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserActionPerformed

    private void tfPWDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPWDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPWDActionPerformed

    private void bSauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSauvegarderActionPerformed
        this.BDHost = tfHost.getText();
        this.BDDBName = tfDBName.getText();
        this.BDUser = tfUser.getText();
        this.BDPWD = tfPWD.getText();
        this.dispose();
    }//GEN-LAST:event_bSauvegarderActionPerformed

    private void bAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_bAnnulerActionPerformed

    private void bAppliquerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAppliquerActionPerformed
        this.BDHost = tfHost.getText();
        this.BDDBName = tfDBName.getText();
        this.BDUser = tfUser.getText();
        this.BDPWD = tfPWD.getText();
    }//GEN-LAST:event_bAppliquerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameConnexion(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnnuler;
    private javax.swing.JButton bAppliquer;
    private javax.swing.JButton bSauvegarder;
    private javax.swing.JLabel lDBName;
    private javax.swing.JLabel lHost;
    private javax.swing.JLabel lPWD;
    private javax.swing.JLabel lUser;
    private javax.swing.JTextField tfDBName;
    private javax.swing.JTextField tfHost;
    private javax.swing.JTextField tfPWD;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
